"""init

Revision ID: 9decf10f5fc0
Revises: 
Create Date: 2026-10-08 20:15:43.215011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9decf10f5fc0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('id_sequences',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ISSUER', 'DOCUMENT_OWNER', 'REVIEWER', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('stored_filename', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('UPLOADED', 'ANALYZING', 'ANALYZED', 'APPROVED', name='lifecyclestatus'), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=True),
    sa.Column('upload_source', sa.Enum('ISSUER_UPLOAD', 'OWNER_UPLOAD', name='uploadsource'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_doc_id'), 'documents', ['doc_id'], unique=True)
    op.create_table('issuers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('organization_type', sa.Enum('UNIVERSITY', 'COLLEGE', 'COMPANY', 'GOVERNMENT', 'TRAINING_INSTITUTE', 'OTHER', name='organizationtype'), nullable=False),
    sa.Column('official_domain', sa.String(), nullable=False),
    sa.Column('official_email', sa.String(), nullable=False),
    sa.Column('registration_reference', sa.String(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'SUSPENDED', name='verificationstatus'), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('action_details', sa.JSON(), nullable=True),
    sa.Column('previous_event_hash', sa.String(), nullable=True),
    sa.Column('current_event_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_document_id'), 'audit_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_table('public_verification_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('verification_id_queried', sa.String(), nullable=False),
    sa.Column('verifier_ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_verification_events_document_id'), 'public_verification_events', ['document_id'], unique=False)
    op.create_table('registration_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('registered_by', sa.String(), nullable=False),
    sa.Column('public_verification_id', sa.String(), nullable=False),
    sa.Column('hmac_token', sa.String(), nullable=False),
    sa.Column('qr_code_path', sa.String(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index(op.f('ix_registration_records_public_verification_id'), 'registration_records', ['public_verification_id'], unique=True)
    op.create_table('review_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_case_id', sa.String(), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='reviewstatus'), nullable=True),
    sa.Column('decision', sa.Enum('APPROVE', 'REJECT', 'REQUEST_NEW_DOCUMENT', 'OVERRIDE_FINDING', name='reviewdecision'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_cases_review_case_id'), 'review_cases', ['review_case_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_cases_review_case_id'), table_name='review_cases')
    op.drop_table('review_cases')
    op.drop_index(op.f('ix_registration_records_public_verification_id'), table_name='registration_records')
    op.drop_table('registration_records')
    op.drop_index(op.f('ix_public_verification_events_document_id'), table_name='public_verification_events')
    op.drop_table('public_verification_events')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_document_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('issuers')
    op.drop_index(op.f('ix_documents_doc_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('id_sequences')
    # ### end Alembic commands ###
