"""add_analysis_fields

Revision ID: d206ee3cb944
Revises: 9decf10f5fc0
Create Date: 2026-10-08 20:16:44.437981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd206ee3cb944'
down_revision: Union[str, None] = '9decf10f5fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('ocr_status', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('document_type', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('document_type_confidence', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('forensic_risk_score', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('forensic_risk_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'forensic_risk_level')
    op.drop_column('documents', 'forensic_risk_score')
    op.drop_column('documents', 'document_type_confidence')
    op.drop_column('documents', 'document_type')
    op.drop_column('documents', 'ocr_status')
    # ### end Alembic commands ###
